name: CI (PRs/Branches)

on:
  push:
    branches-ignore:
      - 'root'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Set up Node
        uses: actions/setup-node@v2-beta

        with:
          node-version: 12

      - name: NPM (Install/Build)
        run: npm i

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Rename Artifacts
        run: |
          mv build/libs/*-all.jar build/libs/KDSite.jar
          mv build/libs/*-*.*.jar build/libs/KDSite-slim.jar

      - name: Upload artifact (Slim JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Slim JAR
          path: build/libs/KDSite-slim.jar

      - name: Upload artifact (Production JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Production JAR
          path: build/libs/KDSite.jar
